CREATE TABLE micro_posts (
  id        SERIAL,
  user_id   BIGINT       NOT NULL,
  content   VARCHAR(140) NOT NULL,
  create_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
)